Fixes the issue of stringify encoding comma(used to join array) even when `encodeValuesOnly = true`
ljharb/qs pull request #424
Opened 2021-11-05 14:49 UTC by adnan-creator

Following changes were made:
* According to the documentation when `encodeValuesOnly = true`, then all characters except the values must not be encoded. This includes brackets and joining characters such as comma. It works perfectly for all other characters except when comma is used to join elements of an array. Then even the comma is encoded. 
* One of the tests had a bug where we assumed the result of `qs.stringify({ a: ['b', 'c', 'd'] }, { arrayFormat: 'comma' })` to be equal to `'a=b,c,d'`. Which is not the expected behavior as for the comma to not be encoded we must either set `encode: false` or `encodeValuesOnly: true`. So the right result would be `'a=b%2Cc%2Cd'` as the default functionality of the function is to encode the complete string.

2021-11-06 05:43 UTC, ljharb requested changes
I rebased this on top of my failing tests branch; take a look at the failures. The `???` will need to be updated to an actual expected value.

2021-11-06 05:43 UTC, ljharb commented on lib/stringify.js
> +            if(generateArrayPrefix === 'comma' && encodeValuesOnly){
nit:
```suggestion
            if (generateArrayPrefix === 'comma' && encodeValuesOnly) {
```

2021-11-06 05:43 UTC, ljharb commented on lib/stringify.js
> +                const valuesArray = String(obj).split(',');
`String(obj)` for a non-array object will turn into `[object Object]`, which i don't think is what we want.

2021-11-09 07:26 UTC, ljharb approved these changes
Overall this looks great!

Are there any additional test cases we should be adding to make sure this is doing both what the issue participants expect, and what we expect?

2021-11-09 07:32 UTC, adnan-creator commented
Thanks! for now these tests seem fine.

2021-11-09 19:07 UTC, ljharb approved these changes

2021-11-09 19:21 UTC, merged