[New] `parse`: call decoder when parsing objects
ljharb/qs pull request #479
Opened 2023-07-28 15:18 UTC by nbgraham

Fixes #284.

2023-08-05 05:44 UTC, ljharb requested changes

2023-08-05 05:44 UTC, ljharb commented on lib/parse.js
> +    }
i think this optimization is actually incorrect, because the default decoder does actual work.
```suggestion
```

2023-08-05 05:44 UTC, ljharb commented on lib/parse.js
> +    var decodedObj = {};
this needs to respect `plainObjects`.
```suggestion
    var decodedObj = opts.plainObjects ? Object.create(null) : {};
```

2023-08-05 05:44 UTC, ljharb commented on test/parse.js
> +        st.deepEqual(qs.parse({
```suggestion
        st.deepEqual(
            qs.parse({
```

2023-08-05 05:44 UTC, ljharb commented on test/parse.js
> +        }, {
```suggestion
        },
        {
```

2023-08-05 05:44 UTC, ljharb commented on test/parse.js
> +        }), {
```suggestion
        }),
        {
```

2023-08-05 05:44 UTC, ljharb commented
This seems like it's either a bugfix - a patch - or a breaking change, in which case it should be implemented behind an option instead.

2023-08-15 14:19 UTC, nbgraham commented
@ljharb 
Based on [this](https://github.com/ljharb/qs/issues/284#issuecomment-426098167) I was treating it as a bugfix. It's kinda already behind the `decoder` option. If you don't provide that, this won't do anything. 
But I guess someone could be providing the `decoder` option today, and this could change the behavior for them.

2023-08-15 16:30 UTC, ljharb commented
That's exactly my concern - especially since this issue was filed *five* years ago and the behavior probably long predates that.

2025-01-14 17:40 UTC, ljharb commented
@nbgraham any interest in completing this PR?

2025-01-17 03:02 UTC, nbgraham commented
> @nbgraham any interest in completing this PR?

No, it doesn't have a clear solution and it's not worth it to me

2025-01-17 03:02 UTC, closed without merging